In [ ]:
#parse single html
import os
os.chdir("B:/Projects/CourseWork/coursework/HTMLCSV/ogimet/data")

from bs4 import BeautifulSoup
soup = BeautifulSoup(open("1999/101999.html", 'rb'), "lxml")
soup = soup.select('body > table> tr:nth-child(2) > td:nth-child(2) > table:nth-child(2) > thead')[0]

#one row

date = soup.select('tr:nth-child(2) > td:nth-child(1) > a')[0].string
time = soup.select('tr:nth-child(2) > td:nth-child(2) > a')[0].string
temp = soup.select('tr:nth-child(2) > td:nth-child(3) > font')[0].string
temp_d = soup.select('tr:nth-child(2) > td:nth-child(4) > font')[0].string
Tmax = soup.select('tr:nth-child(2) > td:nth-child(5)')[0].string
Tmin = soup.select('tr:nth-child(2) > td:nth-child(6)')[0].string
ddd = soup.select('tr:nth-child(2) > td:nth-child(7) > font')[0].string
ff_kmh = soup.select('tr:nth-child(2) > td:nth-child(8) > font')[0].string
Gust_kmh = soup.select('tr:nth-child(2) > td:nth-child(9)')[0].string
P0_hPa = soup.select('tr:nth-child(2) > td:nth-child(10) > font')[0].string
P_sea_hPa = soup.select('tr:nth-child(2) > td:nth-child(11) > font')[0].string
P_Tnd = soup.select('tr:nth-child(2) > td:nth-child(12) > font')[0].string
P_rec = soup.select('tr:nth-child(2) > td:nth-child(13)')[0].string
N_t = soup.select('tr:nth-child(2) > td:nth-child(14) > font')[0].string
N_h = soup.select('tr:nth-child(2) > td:nth-child(15) > font')[0].string
H_Km = soup.select('tr:nth-child(2) > td:nth-child(16) > font')[0].string
Inso_D_1 = soup.select('tr:nth-child(2) > td:nth-child(17)')[0].string
Vis_km = soup.select('tr:nth-child(2) > td:nth-child(18) > font')[0].string

# need update select
Snow = soup.select('tr:nth-child(2) > td:nth-child(19)')[0].string
# and next
WW = soup.select('tr:nth-child(2) > td:nth-child(19) > img')[0]['alt']
W1 = soup.select('tr:nth-child(2) > td:nth-child(20) > img')[0]['alt']
W2 = soup.select('tr:nth-child(2) > td:nth-child(21) > img')[0]['alt']

In [ ]:
# print

print(date, end = ' ')
print(time, end = ' ')
print(temp, end = ' ')
print(temp_d, end = ' ')
print(Tmax, end = ' ')
print(Tmin, end = ' ')
print(ddd, end = ' ')
print(ff_kmh, end = ' ')
print(Gust_kmh, end = ' ')
print(P0_hPa, end = ' ')
print(P_sea_hPa, end = ' ')
print(P_Tnd, end = ' ')
print(P_rec, end = ' ')
print(N_t, end = ' ')
print(N_h, end = ' ')
print(H_Km, end = ' ')
print(Inso_D_1, end = ' ')
print(Vis_km)
print(WW, end = ' ')
print(W1, end = ' ')
print(W2)
print ('---------------')

In [ ]:
soup = BeautifulSoup(open("2002/102002.html", 'rb'), "lxml")
soup = soup.select('body > table> tr:nth-child(2) > td:nth-child(2) > table:nth-child(2) > thead')[0]

for i, tr in enumerate(soup.findAll("tr")):
    if i == 0:
        continue
    date = tr.select('td:nth-child(1) > a')[0].string
    time = tr.select('td:nth-child(2) > a')[0].string
    temp = tr.select('td:nth-child(3) > font')[0].string
    print(date, end = ' ')
    print(time, end = ' ')
    print(temp)

In [ ]:
# reversed and append to dataframe
# append to dataframe
import pandas as pd
data = []
col_names = ['date', 'time', 'temp']


soup = BeautifulSoup(open("2002/102002.html", 'rb'), "lxml")
soup = soup.select('body > table> tr:nth-child(2) > td:nth-child(2) > table:nth-child(2) > thead')[0]

for i, tr in enumerate(reversed(soup.findAll("tr"))):
    if i == len(soup.findAll("tr")) - 1:
        continue
    date = str(tr.select('td:nth-child(1) > a')[0].string)
    time = str(tr.select('td:nth-child(2) > a')[0].string)
    temp = str(tr.select('td:nth-child(3) > font')[0].string)
#     print(date, end = ' ')
#     print(time, end = ' ')
#     print(temp)
    data.append({'date': date, 'time': time, 'temp': temp})
    
df = pd.DataFrame(data, columns = col_names)
df.head(20)

In [ ]:
# station:
soup = BeautifulSoup(open("2002/102002.html", 'rb'), "lxml")
code = soup.select('body > table > tr:nth-child(2) > td:nth-child(2) > table:nth-child(1) > tr > td > h3 > font')[0]
title = soup.select('body > table > tr:nth-child(2) > td:nth-child(2) > table:nth-child(1) > tr > td > h3')[0]
lat = soup.select('body > table > tr:nth-child(2) > td:nth-child(2) > table:nth-child(1) > tr > td > h4 > font:nth-child(1)')[0]
lon = soup.select('body > table > tr:nth-child(2) > td:nth-child(2) > table:nth-child(1) > tr > td > h4 > font:nth-child(2)')[0]
alt = soup.select('body > table > tr:nth-child(2) > td:nth-child(2) > table:nth-child(1) > tr > td > h4 > font:nth-child(3)')[0]
print(code.string)
print(title.string)
print(lat.string)
print(lon.string)
print(alt.string)

In [ ]:
# all files

import os
os.chdir("B:/Projects/CourseWork/coursework/HTMLCSV/ogimet/data")

import pandas as pd
import datetime
import ntpath
from bs4 import BeautifulSoup

m_df = pd.DataFrame()

for year in range(1999, 2020 + 1):
    for month in range(1, 12 + 1):
        file = ''
        try:
            file = open(f'{year}/{month}{year}.html', 'rb')
        except:
            continue
        
        
        # reversed and append to dataframe
        # append to dataframe
        data = []
        col_names = ['date', 'time', 'T', 'Tmax', 'Tmin']

        soup = BeautifulSoup(file, "lxml")
        soup = soup.select('body > table> tr:nth-child(2) > td:nth-child(2) > table:nth-child(2) > thead')[0]

        for i, tr in enumerate(reversed(soup.findAll("tr"))):
            if i == len(soup.findAll("tr")) - 1:
                continue
            try:
                date = str(tr.select('td:nth-child(1) > a')[0].string)
                time = str(tr.select('td:nth-child(2) > a')[0].string)
                T = str(tr.select('td:nth-child(3)')[0].string)
                Tmax = str(tr.select('td:nth-child(5)')[0].string)
                Tmin = str(tr.select('td:nth-child(6)')[0].string)
            #     print(date, end = ' ')
            #     print(time, end = ' ')
            #     print(temp)
                data.append({'date': date, 'time': time, 'T': T, 'Tmax': Tmax, 'Tmin': Tmin})
            except:
                print(file)
                raise

        df = pd.DataFrame(data, columns = col_names)
        if m_df.empty:
            m_df = df
        else:
            m_df = m_df.append(df, ignore_index=True)

m_df.drop_duplicates()
m_df.to_csv('weather.csv')

In [121]:
# load
import pandas as pd
import numpy as np
import os
os.chdir("B:/Projects/CourseWork/coursework/HTMLCSV/ogimet/data")

df = pd.read_csv('weather.csv')
df = df.drop(df.columns[0], axis=1)
df['date'] = pd.to_datetime(df['date'], format="%m/%d/%Y")
df['time'] = pd.to_datetime(df.time,format='%H:%M').dt.time

# replace '-----' to nan
df['T'].replace('-----', np.nan, inplace=True)
df['Tmax'].replace('-----', np.nan, inplace=True)
df['Tmin'].replace('-----', np.nan, inplace=True)

df['T'] = df['T'].astype(float)
df['Tmax'] = df['Tmax'].astype(float)
df['Tmin'] = df['Tmin'].astype(float)

df.tail(100)

            date      time     T  Tmax  Tmin
60539 2020-01-30  09:00:00 -18.2   NaN   NaN
60540 2020-01-30  12:00:00 -20.3   NaN   NaN
60541 2020-01-30  15:00:00 -23.5 -17.6   NaN
60542 2020-01-30  18:00:00 -24.0   NaN   NaN
60543 2020-01-30  21:00:00 -24.0   NaN   NaN
60544 2020-01-31  00:00:00 -22.7   NaN   NaN
60545 2020-01-31  03:00:00 -25.8   NaN -29.6
60546 2020-01-31  06:00:00 -17.5   NaN   NaN
60547 2020-01-31  09:00:00 -15.3   NaN   NaN
60548 2020-01-31  12:00:00 -17.2   NaN   NaN
60549 2020-01-31  15:00:00 -18.1 -14.9   NaN
60550 2020-01-31  18:00:00 -18.8   NaN   NaN
60551 2020-01-31  21:00:00 -19.1   NaN   NaN
60552 2020-02-01  00:00:00 -20.9   NaN   NaN
60553 2020-02-01  03:00:00 -20.7   NaN -21.1
60554 2020-02-01  06:00:00 -17.8   NaN   NaN
60555 2020-02-01  09:00:00 -14.9   NaN   NaN
60556 2020-02-01  12:00:00 -16.4   NaN   NaN
60557 2020-02-01  15:00:00 -16.5 -14.6   NaN
60558 2020-02-01  18:00:00 -16.2   NaN   NaN
60559 2020-01-30  18:00:00 -24.0   NaN   NaN
60560 2020-01-30  21:00:00 -24.0   NaN   NaN
60561 2020-01-31  00:00:00 -22.7   NaN   NaN
60562 2020-01-31  03:00:00 -25.8   NaN -29.6
60563 2020-01-31  06:00:00 -17.5   NaN   NaN
60564 2020-01-31  09:00:00 -15.3   NaN   NaN
60565 2020-01-31  12:00:00 -17.2   NaN   NaN
60566 2020-01-31  15:00:00 -18.1 -14.9   NaN
60567 2020-01-31  18:00:00 -18.8   NaN   NaN
60568 2020-01-31  21:00:00 -19.1   NaN   NaN
...          ...       ...   ...   ...   ...
60609 2020-02-06  00:00:00  -1.6   NaN   NaN
60610 2020-02-06  03:00:00  -1.6   NaN  -1.9
60611 2020-02-06  06:00:00  -3.6   NaN  -3.6
60612 2020-02-06  09:00:00  -5.0   NaN   NaN
60613 2020-02-06  12:00:00  -6.6   NaN   NaN
60614 2020-02-06  15:00:00  -7.8   0.3   NaN
60615 2020-02-06  18:00:00  -7.1   NaN   NaN
60616 2020-02-06  21:00:00  -5.7   NaN   NaN
60617 2020-02-07  00:00:00  -6.1   NaN   NaN
60618 2020-02-07  03:00:00  -6.1   NaN  -7.8
60619 2020-02-07  06:00:00  -3.9   NaN   NaN
60620 2020-02-07  09:00:00  -2.4   NaN   NaN
60621 2020-02-07  12:00:00  -3.2   NaN   NaN
60622 2020-02-07  15:00:00  -4.1  -2.2   NaN
60623 2020-02-07  18:00:00  -5.0   NaN   NaN
60624 2020-02-07  21:00:00  -3.6   NaN   NaN
60625 2020-02-08  00:00:00   0.1   NaN   NaN
60626 2020-02-08  03:00:00   0.7   NaN  -5.0
60627 2020-02-08  06:00:00   0.8   NaN   NaN
60628 2020-02-08  09:00:00   1.3   NaN   NaN
60629 2020-02-08  12:00:00   1.1   NaN   NaN
60630 2020-02-08  15:00:00   0.4   1.6   NaN
60631 2020-02-08  18:00:00  -1.9   NaN   NaN
60632 2020-02-08  21:00:00  -4.1   NaN   NaN
60633 2020-02-09  00:00:00  -5.6   NaN   NaN
60634 2020-02-09  03:00:00  -8.1   NaN  -8.1
60635 2020-02-09  06:00:00  -9.5   NaN -10.0
60636 2020-02-09  09:00:00  -9.4   NaN   NaN
60637 2020-02-09  12:00:00 -11.3   NaN   NaN
60638 2020-02-09  15:00:00 -13.1  -8.1   NaN

[100 rows x 5 columns]

In [ ]:
# finding dublicates
#m_df.drop_duplicates() # incorrect work

# Select duplicate rows except first occurrence based on all columns
#duplicateRowsDF = df[df.duplicated()]
#duplicateRowsDF = df[df.duplicated(['date', 'time'])]

# drop dublicates
df.drop_duplicates(subset =['date','time'], 
                     keep = False, inplace = True) 
df.info()
# replace incorrect values
df['T'].replace(50.2, np.nan, inplace=True)
df['T'].replace(-90.4, np.nan, inplace=True)
df['T'].replace(-88.0, np.nan, inplace=True)
df['T'].replace(-48.8, np.nan, inplace=True)

In [ ]:
# analysis
df.loc[df['T'] < -39]

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60639 entries, 0 to 60638
Data columns (total 5 columns):
date    60639 non-null object
time    60639 non-null datetime64[ns]
T       60574 non-null float64
Tmax    12381 non-null float64
Tmin    7843 non-null float64
dtypes: datetime64[ns](1), float64(3), object(1)
memory usage: 2.3+ MB